// File generated by FlutterFire CLI.
// This is a placeholder - run `flutterfire configure` to generate real values

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYtFUaZoSiYS-uh7qOJXPvsinmOlvvJ1U',
    appId: '1:520080359838:android:f18d5c6d4337276683168f',
    messagingSenderId: '520080359838',
    projectId: 'pro-score-line',
    storageBucket: 'pro-score-line.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtFUaZoSiYS-uh7qOJXPvsinmOlvvJ1U',
    appId: '1:520080359838:ios:f18d5c6d4337276683168f',
    messagingSenderId: '520080359838',
    projectId: 'pro-score-line',
    storageBucket: 'pro-score-line.firebasestorage.app',
    iosBundleId: 'com.brighthex.dream247',
  );
}
